### ISSUE TITLE
Can basePath be a standard of rdl format?

### ISSUE THREAD

**Issue by joejoe321321** [ardielle/ardielle-tools#69]
HI, we are using rdl as our framework implementation.
Some users want the feature of basePath to be a part of rdl, so they can set path for each rdl file.

We know there are parameter "-b" in the generator of client & server, but it is not enough for us.
Can basePath be a field in generated json file?
We want it to be like what swagger supported. http://swagger.io/specification/

It will do us a big favor. 
Thank you.

**Comment by boynton** [comment]
This feature be probably be added (are you asking specifically for it to be called "basePath"? I'd prefer no mixed case keywords in RDL). It has to work in a predictable way across included files, also (i.e. a file with a base path includes another file with another base path), have you thought of how that should be handled?

**Comment by joejoe321321** [comment]
We surveyed the current behavior of rdl. It will ignore "name" or "version" tags in included files, even when these tags are missing in the child rdl file. We thought It is also a proper way to handle "basePath" tag. Just ignore the key in included files.

For the first question, the keyword "bashPath" can be changed. Use another keyword to prevent a confusion is fine for us. 

Thank you for the help.

**Comment by boynton** [comment]
Fixed in commit b436a6cc54ca503c02c7af89dc32e53959cb06b9.

Added the "base" option. Usage is:

...
name something;
version 2;
base "/some/path";
...

If no base is specified, a default base is generated as before.

The swagger generator now includes this (the -b option overrides the schema base), and the new swagger importer preserves it.

**Comment by joejoe321321** [comment]
Thanks for your kindly help.
We'll waiting for it in 1.4.12 release.
