### ISSUE TITLE
print the name of queryparam on validation failure

### ISSUE THREAD

**Issue by dmitris** [ardielle/ardielle-tools#7]
I'm getting an error trying to generate the server bindings:
```
RDL error: queryparam must either be optional or have a default value
```
- but it does not say which queryparam is causing problems, which would help to troubleshoot.

(I also then figured out that the failure was caused by misspelled 'optional' - had 'optinal' instead; should the compiler indicate that it is an unknown option?)

**Comment by boynton** [comment]
Yes, the error msg could be better, and yes, it should reject any non-"X_*" type options.
