### ISSUE TITLE
[markdown generator] wrong anchor. 

### ISSUE THREAD

**Issue by geekybaiyi** [ardielle/ardielle-tools#83]
please refer to a simple rdl and the generated markdown https://gist.github.com/geekybaiyi/1a1b214ea6403e6c6981c81b898ff2e0

Under `Types` -> `Users`, it refers to the type `User`.  However it links to the anchor on the Resource that returns `User`, not link to the `User` type.
However wouldn't it makes more sense to link to the `User` type in this context ?

**Comment by geekybaiyi** [comment]
Thanks for the fix.  Will there be a new release available?

**Comment by boynton** [comment]
Soon, seeing if some other fixes are close enough.
