### ISSUE TITLE
Generated go code for rdl with more than one enums with same value is unusable

### ISSUE THREAD

**Issue by ranjithkumarshetty** [ardielle/ardielle-tools#93]
Following is the example where I have 2 enums `myEnumA` and `myEnumB` defined in the same .rdl file and the code for types in the schema is generated.

*$ cat example.rdl*
namespace example;

type myEnumA Enum { ALL, ENUM_A_VALUE1 }
type myEnumB Enum { ALL, ENUM_B_VALUE2 }

*$ rdl generate java-model example.rdl*
*$ rdl generate go-model example.rdl*

Java files created for EnumA and EnumB are
*$ ls src/main/java/example/MyEnum**
src/main/java/example/MyEnumA.java	src/main/java/example/MyEnumB.java

Java generated code has no issue, works fine for me.

Go file created
*$ ls example_model.go*
example_model.go

```
//
// myEnumA -
//
type MyEnumA int

//
// MyEnumA constants
//
const (
        _ MyEnumA = iota
        ALL
        ENUM_A_VALUE1
)

var namesMyEnumA = []string{
        ALL:           "ALL",
        ENUM_A_VALUE1: "ENUM_A_VALUE1",
}

//
// myEnumB -
//
type MyEnumB int

//
// MyEnumB constants
//
const (
        _ MyEnumB = iota
        ALL
        ENUM_B_VALUE2
)

var namesMyEnumB = []string{
        ALL:           "ALL",
        ENUM_B_VALUE2: "ENUM_B_VALUE2",
}
```

------
Since `ALL` is redeclared in the block using this model gives me the error

```
./example_model.go:109: ALL redeclared in this block
	previous declaration at ./example_model.go:25
```

**Comment by dmitris** [comment]
what do you think should be the code for Go to generate?  Prepend the names with the type name - like `myEnumA_ALL`?

**Comment by ranjithkumarshetty** [comment]
Yeah, I think having the prefix makes it unique
```
//
// myEnumA -
//
type MyEnumA int

//
// MyEnumA constants
//
const (
	_ MyEnumA = iota
	MyEnumA_ALL
	MyEnumA_ENUM_A_VALUE1
)

var namesMyEnumA = []string{
	MyEnumA_ALL:           "ALL",
	MyEnumA_ENUM_A_VALUE1: "ENUM_A_VALUE1",
}


//
// myEnumB -
//
type MyEnumB int

//
// MyEnumB constants
//
const (
	_ MyEnumB = iota
	MyEnumB_ALL
	MyEnumB_ENUM_B_VALUE2
)

var namesMyEnumB = []string{
	MyEnumB_ALL:           "ALL",
	MyEnumB_ENUM_B_VALUE2: "ENUM_B_VALUE2",
}
```

Here are the equivalent Java enums:
Filename: MyEnumA.java
```
//
// This file generated by rdl 1.4.12. Do not modify!
//

package example;
import com.yahoo.rdl.*;

//
// myEnumA -
//
public enum MyEnumA {
    ALL,
    ENUM_A_VALUE1;

    public static MyEnumA fromString(String v) {
        for (MyEnumA e : values()) {
            if (e.toString().equals(v)) {
                return e;
            }
        }
        throw new IllegalArgumentException("Invalid string representation for MyEnumA: " + v);
    }
}
```
Filename: MyEnumB.java
```
//
// This file generated by rdl 1.4.12. Do not modify!
//

package example;
import com.yahoo.rdl.*;

//
// myEnumB -
//
public enum MyEnumB {
    ALL,
    ENUM_B_VALUE2;

    public static MyEnumB fromString(String v) {
        for (MyEnumB e : values()) {
            if (e.toString().equals(v)) {
                return e;
            }
        }
        throw new IllegalArgumentException("Invalid string representation for MyEnumB: " + v);
    }
}
```

**Comment by dmitris** [comment]
> having the prefix makes it unique

would this break backward compatibility (since generated code in a new version would be different from the previous one on an unchanged template)?  If so, do we think it is acceptable?

**Comment by ranjithkumarshetty** [comment]
It would most definitely break the backward compatibility, I am not sure if we have a way to support this feature without breaking it 😞

**Comment by boynton** [comment]
The -e option to the generator is meant to handle this case. See the RDL usage line:

  -e              Generate Enum constants prefixed by the type name to avoid collisions (default is false)

This feature has been there since before the open source release (over 2 years now).
